### ISSUE TITLE
number of parameters in E_(h/2) step

### ISSUE THREAD

**Issue by yuanqing-wang** [TiffanyVlaar/ThermodynamicParameterizationOfNNs#1]
Hi @TiffanyVlaar !

It seems that in your implementation, the number of parameters (N) in your E_(h/2) step for the first layer was set to 100 for this example. Although this might not make that much of a difference, wouldn't it be the the true degrees of freedom, which in this case would be 2 * 100 for the weight in this layer?

Thanks!

**Comment by TiffanyVlaar** [comment]
Yes, thanks for spotting that. It's corrected now!
